apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-go-rhtap-three-component-scenarios
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-comp-e2e-coxi-tenant/mc-three-scenarios/devfile-go-rhtap-three-component-scenarios@sha256:40725ef896a0a7e9eb80d24c6168e807789590eafaf8a38e6caad31d6e246137
        name: my-go
        resources: {}
status: {}
